server:
  contextPath: '/'
  server:
    port: 8082

spring:
  mail:
    default-encoding: UTF-8
    host: mail.flowdaq.com
    port: 587
    username: noreply@flowdaq.com
    password: 57u0TWsG
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: mail.flowdaq.com    

  resources: 
    static-locations: 'classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/webui/'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flowdaq?serverTimezone=UTC 
    username: cicoda_001  
    password: cogNIT!31847_ 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: flowdaq-demo
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true  
springfox:
  documentation:
    swagger:
      v2:
        path: '/api-docs'   
 
flowdaq:
  app:
    security:
      jwt:
        issuer: flowdaq  
        expiration-sec: 100  
        clock-skew-sec: 3000 
        secret: some_secret!changeMe
